name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@dabb1b52d35733fde278c288e4781d4336d4c29c
      - name: Build with Gradle
        uses: gradle/gradle-build-action@e0391a3985c5396bc53ae94af1ee0cf7c37da07b
        with:
          arguments: build
